package com.pm.analyticsservice.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import java.util.List;
import java.util.Map;

@Service
public class GeminiService {

    @Value("${gemini.api.key}")
    private String apiKey;

    @Value("${gemini.api.url:https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent}")
    private String geminiUrl;

    private final RestClient restClient;

    public GeminiService() {
        this.restClient = RestClient.builder().build();
    }

    public String generateText(String prompt) {
        if (apiKey == null || apiKey.isBlank()) {
            throw new IllegalStateException("Gemini API key is missing. Please configure GEMINI_API_KEY environment variable.");
        }

        if (prompt == null || prompt.isBlank()) {
            return "Prompt cannot be empty.";
        }

        // Bound prompt length to prevent resource exhaustion / large payloads
        if (prompt.length() > 4000) {
            prompt = prompt.substring(0, 4000);
        }

        Map<String, Object> requestBody = Map.of(
            "contents", List.of(
                Map.of(
                    "parts", List.of(
                        Map.of("text", prompt)
                    )
                )
            )
        );

        try {
            // SECURITY FIX: Send key via x-goog-api-key HTTP header instead of URL query parameter
            Map<String, Object> response = restClient.post()
                    .uri(geminiUrl)
                    .header("x-goog-api-key", apiKey)
                    .contentType(MediaType.APPLICATION_JSON)
                    .body(requestBody)
                    .retrieve()
                    .body(Map.class);

            if (response != null && response.containsKey("candidates")) {
                List<?> candidates = (List<?>) response.get("candidates");
                if (!candidates.isEmpty()) {
                    Map<?, ?> firstCandidate = (Map<?, ?>) candidates.get(0);
                    Map<?, ?> content = (Map<?, ?>) firstCandidate.get("content");
                    if (content != null && content.containsKey("parts")) {
                        List<?> parts = (List<?>) content.get("parts");
                        if (!parts.isEmpty()) {
                            Map<?, ?> firstPart = (Map<?, ?>) parts.get(0);
                            return (String) firstPart.get("text");
                        }
                    }
                }
            }
            return "No text response generated by Gemini.";
        } catch (Exception e) {
            // Generic error message returned to user to avoid leaking internal exception details
            return "Unable to process request with AI service at this time.";
        }
    }
}
