### GET request to get all patients
GET http://localhost:4005/api/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzU4NzA2NiwiZXhwIjoxNzU3NjIzMDY2fQ.I3Vn3uS3P9p91A9aW5IgjnxnI9oN1tSZ-XFA9coIF8o

###